baseURL = "https://alinedoula.com/"
languageCode = "en-us"
title = "Aline Doula"
theme = "hallo"

[Author]
    name = "Aline Oliveira (she/her)"

[params]
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://www.instagram.com/asantoliveira/"
    [[params.links]]
        icon = "facebook"
        title = "Facebook"
        url = "https://www.facebook.com/aline.amamenta"
    [params.colors]
        background = "#7aa6cb"
        foreground = "#edf7ff"
        hover = "#f2c584"
