baseURL = "http://alinedoula.github.io/"
languageCode = "en-us"
title = "Aline Doula"
theme = "hallo"

[Author]
    name = "Aline Oliveira (she/her)"

[params]
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://www.instagram.com/asantoliveira/"
